#!/usr/bin/env ruby
require 'config.rb'
require 'fileutils'

if not ARGV[0]
  raise "Provide an argument"
end

files = ["#{ARGV[0]}.key", "#{ARGV[0]}.crt", "ca.crt", "ta.key"]

files.each do |file|
  if not File.exists?("#{CA_DIR}/#{file}")
    raise "File #{file} does not exist"
  end
end

dir = "#{ARGV[0]}.tblk"

if File.directory?(dir)
  raise "Directory #{dir} exists"
end

FileUtils.mkdir_p("#{dir}/Contents/Resources")

files.each do |file|
  FileUtils.copy("#{CA_DIR}/#{file}", "#{dir}/Contents/Resources/#{file}")
end

config = %{
client
dev tun
proto udp
remote #{HOST} 1194
resolv-retry infinite
nobind
persist-key
persist-tun
ca ca.crt
cert #{ARGV[0]}.crt
key #{ARGV[0]}.key
ns-cert-type server
tls-auth ta.key 1
cipher AES-256-CBC
comp-lzo
verb 3
ping 10
ping-restart 60
explicit-exit-notify 2
}

File.open("#{dir}/Contents/Resources/config.ovpn", 'w') do |f|
  f.write(config)
end

`zip -r #{dir}.zip ./#{dir}`
FileUtils.rm_rf dir
